### ISSUE TITLE
Database collection schemas

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-api#5]
I took a first stab at designing database schemas for the core collections:

![schema](https://cloud.githubusercontent.com/assets/6340841/18031348/92ecd6b4-6caa-11e6-8462-6288fafca156.jpeg)

**Comment by dsernst** [comment]
voters:
```
// registered users in the system
uid: String,
full_name: String,
email: String,
date_joined: Date,
zip: Number,
local_jurisdiction: jurisdiction_uid,
state_jurisdiction: jurisdiction_uid,
smartphone: ['iOS', 'Android', 'Other', 'none'],
local_delegate: voter_uid,
state_delegate: voter_uid,
national_delegate: voter_uid,
```

jurisdictions:
```
uid: String,
name: String,
level: ['local', 'state', 'national'],
```

bills:
```
uid: String,
jurisdiction: jurisdiction_uid
name: String,
author: String,
body: String,
date_introduced: Date,
date_voted: Date,
LD_for: Number,
LD_against: Number,
LD_abstain: Number,
reps_for: Number,
reps_against: Number,
reps_abstain: Number,
```

votes:
```
// anytime a user explicitly votes on a bill
uid: String,
voter: voter_uid,
bill: bill_uid,
position: ['for', 'against', 'abstain'],
date: Date,
```

**Comment by dsernst** [comment]
We'll need a collection to store login sessions.

sessions:
```
// for each authenticated device
uid: String,
user_id: voter_uid,
date_created: Date,
expiration_date: Date,
```

**Comment by jaredscheib** [comment]
Thanks for working on all of this.

Some of these questions may be beyond the scope of MVP, but seem worth considering since we're defining a schema:
1. Seems like there may be more than one delegate, such as per-issue, for local/state/national?
2. How do we keep track of history, such as if someone changes their zip code over time, or changes delegates?
3. Will the schema change if we end up going with a graph database?
4. Do we want bills to track delegated votes vs. direct votes?
5. Will bills pass by 50%+1 majority? Or, if it may vary, might we include the passing rules on a bill? And a boolean for whether it passed? Or could there be other end-states?
6. Might the bill have other data, such as the date it becomes law? Or could it somehow carry a reference to OpenGov's UID so that kind of data can be quickly looked up?
7. A voter could be considered to have cast a vote at every bill, even if it's delegated or abstained, and there could be a boolean for _delegated_, and a delegate ID, for that vote?

**Comment by dsernst** [comment]
> 1) Seems like there may be more than one delegate, such as per-issue, for local/state/national?

Out of scope for MVP.


> 2) How do we keep track of history, such as if someone changes their zip code over time, or changes delegates?

This is a little tricky because we don't have a use for that history right now, but the short answer is to store logs of all requests. That leaves a non-duplicated history of interaction, so these sorts of things can be recovered later if needed. Also super valuable for metrics and diagnosing problems.


> 3) Will the schema change if we end up going with a graph database?

Not really. The graph database will still be a bunch of nodes with objects that look similar. The edges would just be defined more explicitly to the db rather than just being another field.

> 4) Do we want bills to track delegated votes vs. direct votes?

Yep. See [the working example from the `demo` repo](https://github.com/liquidvote/demo/blob/857ceca43714457fae05da477534c6bff4a068cc/tally-votes.js#L27), which was updated for this.

> 5) Will bills pass by 50%+1 majority? Or, if it may vary, might we include the passing rules on a bill?

It's the legislative bodies' rules already set by the Representative Democracy, out of our control. Don't see how it would vary. 

> And a boolean for whether it passed? Or could there be other end-states?

If I remember correctly, GovTrack does something like a `status` field with enums like `passed`, `failed`, `pending`.

> 6) Might the bill have other data, such as the date it becomes law? Or could it somehow carry a reference to GovTrack / OpenGov UID so that kind of data can be quickly looked up?

Yep.

> 7) A voter could be considered to have cast a vote at every bill, even if it's delegated or abstained, and there could be a boolean for delegated, and a delegate ID, for that vote?

Unclear question. Are you asking if it makes sense to create a row for every vote, including delegated ones?

**Comment by dsernst** [comment]
Closing this bc it was originally meant only as a placeholder for those legal-pad notes. There's no real issue here to be solved.

Don't mean to shut down your questions though, @jaredscheib. Feel free to create a new issue or whatnot for any of them if you think it's still unclear and important at this time.
